[Common]
UserName=Ed Taylor
Person=C:\DIV_MAP\
Server=UnEMBa11
PickTest=1
PickVal=4
Local=C:\data\ACCESS\Adds_Oracle_XP.mdb
Main=S:\Workgroups\APC Power Delivery\Division Mapping\Adds Data\APC_Panel.mdb

[ADDS]
TMult=100
SMult=100
Server=PnEmbG1
UserName=Roger Ivester
Person=C:\DIV_MAP\
DwtNam=C:\Div_Map\LookUpTable\Template\Adds.dwt
Dwg=S:\Workgroups\GPC Real-Time Systems\STAFF\Transmap\ADDS_TMap\Adds\DWG\
Dwf=S:\Workgroups\GPC Real-Time Systems\STAFF\Transmap\ADDS_TMap\Adds\DWF\
UserP=C:\Div_Map\Adds\User\
Plot=S:\Workgroups\GPC Real-Time Systems\STAFF\Transmap\ADDS_TMap\Adds\PLOT\
Lisp=C:\Div_Map\Adds\Lisp\
LUT=C:\Div_Map\LookUpTable\
Menu=C:\Div_Map\Adds\Menu\
Sym=C:\Div_Map\Adds\Sym\
DLG=C:\Div_Map\Quad\
BH.Division=S:\WorkGroups\APC Birmingham Division\Division Mapping\Adds\Panel\
E_.Division=S:\WorkGroups\APC Eastern Division\Division Mapping\Adds\Panel\
M_.Division=S:\WorkGroups\APC Mobile Division\Division Mapping\Adds\Panel\
S_.Division=S:\WorkGroups\APC Southern Division\Division Mapping\Adds\Panel\
SE.Division=S:\WorkGroups\APC SouthEast Division\Division Mapping\Adds\Panel\
W_.Division=S:\WorkGroups\APC Western Division\Division Mapping\Adds\Panel\
AL.Division=S:\Workgroups\APC Power Delivery-ACC\Transmap\ADDS_TMap\Adds\Panel\
GA.Division=*S:\Workgroups\GPC Real-Time Systems\STAFF\Transmap\ADDS_TMap\Adds\Panel\
SndPick01Test=1
SndPick01Val=-1
SndPick02Test=1
SndPick02Val=34
WarnSize=5


[COM25A]
SndPick01Test=1
SndPick01Val=34

[LOGIN]
DBDefault=UnEMBA11 ACC_User1/UnEMBA11
DBName=UnEMBA12 ACC_User2/UnEMBA12
DBName=UnEMBG11 GCC_User1/UnEMBg11
DBName=UnEMBG12 GCC_User2/UnEMBg12


; Allow user to use Network password to log in and automatically change Oracle password to match
;LoginLogic=Old
; Force user to login using Oracle password.
LoginLogic=New


