-- ADDS Oracle Schema - Oracle 11g compatible
-- Created: 1991, last modified: 2008

CREATE SEQUENCE SEQ_ROUTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HX    START WITH 1 INCREMENT BY 1;

CREATE TABLE EQUIPMENT (
    TAG          VARCHAR2(20) PRIMARY KEY,
    TYPE         VARCHAR2(20) NOT NULL,
    MODEL        VARCHAR2(50),
    LOCATION     VARCHAR2(200),
    CREATED_BY   VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    MODIFIED     DATE
);

CREATE TABLE PIPE_ROUTES (
    ROUTE_ID   NUMBER PRIMARY KEY,
    TAG        VARCHAR2(20),
    SPEC       VARCHAR2(30),
    START_PT   VARCHAR2(100),
    END_PT     VARCHAR2(100),
    LENGTH     NUMBER,
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE INSTRUMENTS (
    TAG          VARCHAR2(20) PRIMARY KEY,
    INSTR_TYPE   VARCHAR2(10),
    AREA         VARCHAR2(20),
    POS_X        NUMBER,
    POS_Y        NUMBER,
    LAST_VALUE   VARCHAR2(50),
    TIMESTAMP    DATE,
    CREATED_BY   VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED      DATE
);

CREATE TABLE VESSELS (
    TAG        VARCHAR2(20) PRIMARY KEY,
    CTR_X      NUMBER,
    CTR_Y      NUMBER,
    RADIUS     NUMBER,
    CREATED_BY VARCHAR2(30),
    CREATED_DATE DATE DEFAULT SYSDATE
);

-- No indexes on foreign-key-like columns - performance issue
-- No referential integrity - orphan records accumulate over decades
